[package]
name = "browsy_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
scraper = "0.13.0"

# In project dependencies
browsy_helpers = {path = "../browsy_helpers"}
